#!/usr/bin/python3.12
"""Generate docs/CLASSES.md from docs/class_descriptions.yaml and src/cellsurface_sorting_hat/categories.yaml.

Usage: make_classes_md.py [--write]   (prints the file; --write overwrites docs/CLASSES.md)
"""

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))


def render(desc, cfg):
    order = [c["name"] for c in cfg.calls]
    by = {d["call"]: d for d in desc["calls"]}
    lines = [
        "# Calls of `cellsurface_sorting_hat` (v1)",
        "",
        "*Generated by `analysis/class_table/make_classes_md.py` from `docs/class_descriptions.yaml` and `src/cellsurface_sorting_hat/categories.yaml`. Do not edit by hand; a test checks that this file is current.*",
        "",
        "Evidence calls say what a tool found. Composites (`_candidate`) say what a rule combined. `other_*` calls are the residual categories.",
        "A status holds for one species and taxon and only where its status file is installed and current:",
        "`unvalidated` (no measurement), `smoke` (too little truth for a number), `estimated` (enough truth).",
        "",
        "| call | kind | gated | category | meaning | reads | status |",
        "|---|---|---|---|---|---|---|",
    ]
    for name in order:
        d = by[name]
        lines.append(
            f"| `{name}` | {d['kind']} | {'yes' if d['gated'] else 'no'} | {d['category']} | {d['meaning']} | {', '.join(d['reads'])} | {d['status']} |"
        )
    lines += ["", "## Status files cited (committed)", ""]
    for name in order:
        for path in by[name].get("status_files", []):
            lines.append(f"- `{name}`: `{path}`")
    lines += ["", "## Modules that no call reads (evidence fields or experimental)", ""]
    for m in desc["modules_not_calls"]:
        lines.append(f"- `{m['module']}`: {m['note']}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    from cellsurface_sorting_hat.engine import load_config

    text = render(
        yaml.safe_load((ROOT / "docs/class_descriptions.yaml").read_text()), load_config()
    )
    if a.write:
        (ROOT / "docs/CLASSES.md").write_text(text)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
