#!/usr/bin/env python
"""Assemble REPORT.md from the tables/figures already generated by 01-06.
Pulls all numbers directly from the CSVs. The "Headline findings" and
"Caveats" prose below was written by hand after inspecting the real
output (per the plan's Task 10 Step 2/3), then baked into this script as
a literal string -- NOT left as a runtime placeholder -- so that
re-running this script reproduces the committed REPORT.md exactly. This
is the same pattern actually used by adhesion_properties/06_generate_report.py
(its hand-written prose is baked into that script too, not regenerated
from a placeholder each run) -- a whole-branch review found an earlier
version of this script left the placeholder in place, which would have
silently deleted the report's conclusions on any re-run."""

from pathlib import Path

import pandas as pd

BASE = Path(__file__).resolve().parent
TABLES = BASE / "tables"
FIGURES = BASE / "figures"

SPACES = ["esm2_classifier", "esmc300m"]
SPACE_LABELS = {"esm2_classifier": "ESM2-classifier", "esmc300m": "ESM-C 300M"}


def _scope_stats(space: str) -> dict:
    summary = pd.read_csv(TABLES / f"cluster_summary_{space}.csv")
    n_proteins = int(summary["n"].sum())
    n_clusters = int((summary["cluster_label"] != -1).sum())
    noise_row = summary.loc[summary["cluster_label"] == -1, "n"]
    n_noise = int(noise_row.iloc[0]) if not noise_row.empty else 0
    return {
        "n_proteins": n_proteins,
        "n_clusters": n_clusters,
        "n_noise": n_noise,
        "pct_noise": 100 * n_noise / n_proteins if n_proteins else 0.0,
    }


def _to_markdown_table(df: pd.DataFrame) -> str:
    """Minimal dependency-free markdown table renderer (no `tabulate`
    package available in this environment)."""

    def fmt(v: object) -> str:
        if isinstance(v, float):
            return f"{v:.4f}"
        return str(v)

    cols = list(df.columns)
    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join(["---"] * len(cols)) + " |"
    rows = ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, sep] + rows)


def _cluster_summary_md(space: str, max_rows: int = 15) -> str:
    summary = pd.read_csv(TABLES / f"cluster_summary_{space}.csv")
    summary = summary.sort_values("n", ascending=False).reset_index(drop=True)
    shown = summary.head(max_rows)
    md = _to_markdown_table(shown)
    if len(summary) > max_rows:
        md += (
            f"\n\n(showing top {max_rows} of {len(summary)} rows, sorted by n; "
            f"full table in `tables/cluster_summary_{space}.csv`)"
        )
    return md


def _contingency_summary(ct_path: Path) -> str:
    ct = pd.read_csv(ct_path, index_col=0)
    ct.index = ct.index.astype(int)
    n_rows_a, n_cols_b = ct.shape
    total = ct.values.sum()

    lines = [
        f"Shape: {n_rows_a} ESM2-classifier cluster labels (rows, including noise) x "
        f"{n_cols_b} ESM-C 300M cluster labels (columns, including noise), covering "
        f"{int(total)} proteins with cluster assignments in both spaces."
    ]

    if 0 in ct.index:
        row0 = ct.loc[0]
        row0_total = int(row0.sum())
        # columns are string-typed from CSV round trip; handle both
        noise_col = "-1" if "-1" in row0.index else (-1 if -1 in row0.index else None)
        row0_noise = int(row0[noise_col]) if noise_col is not None else 0
        non_noise = row0.drop(labels=[noise_col]) if noise_col is not None else row0
        n_nonzero_cols = int((non_noise > 0).sum())
        max_cell = int(non_noise.max()) if len(non_noise) else 0
        lines.append(
            f"- ESM2-classifier's dominant cluster (label 0, n={row0_total}) spreads across "
            f"{n_nonzero_cols} of {len(non_noise)} real ESM-C clusters: "
            f"{row0_noise} ({100 * row0_noise / row0_total:.1f}%) land in ESM-C noise, and the "
            f"largest single non-noise cell is only {max_cell} proteins "
            f"({100 * max_cell / row0_total:.2f}% of the cluster) -- ESM-C's fine clustering "
            "resolves internal structure that ESM2-classifier space cannot distinguish."
        )
    if -1 in ct.index:
        rown = ct.loc[-1]
        rown_total = int(rown.sum())
        noise_col = "-1" if "-1" in rown.index else (-1 if -1 in rown.index else None)
        rown_noise = int(rown[noise_col]) if noise_col is not None else 0
        lines.append(
            f"- ESM2-classifier's noise row (n={rown_total}) concentrates heavily in ESM-C "
            f"noise too ({rown_noise}/{rown_total} = {100 * rown_noise / rown_total:.1f}%) -- "
            "the two spaces largely agree on which proteins don't fit any cluster."
        )
    if 1 in ct.index:
        row1 = ct.loc[1]
        row1_total = int(row1.sum())
        top = row1.sort_values(ascending=False)
        top_col, top_val = top.index[0], int(top.iloc[0])
        lines.append(
            f"- ESM2-classifier's tiny second cluster (label 1, n={row1_total}) concentrates "
            f"{top_val}/{row1_total} ({100 * top_val / row1_total:.1f}%) of its members onto a "
            f"single ESM-C cluster (label {top_col}) -- see Headline findings for what that "
            "ESM-C cluster's property/domain profile shows."
        )
    return "\n".join(lines)


def _aa1_summary(space: str) -> str:
    df = pd.read_csv(TABLES / f"aa1_concentration_by_cluster_{space}.csv")
    n_clusters = len(df)
    frac_zero = int((df["fraction"] == 0).sum())
    frac_one = int((df["fraction"] == 1).sum())
    std = df["fraction"].std()
    lines = [
        f"- {n_clusters} rows (one per cluster label, including noise).",
        f"- {frac_zero}/{n_clusters} ({100 * frac_zero / n_clusters:.1f}%) at fraction=0.0, "
        f"{frac_one}/{n_clusters} ({100 * frac_one / n_clusters:.1f}%) at fraction=1.0.",
        f"- std of per-cluster `has_cazy` fraction: {std:.3f}.",
    ]
    return "\n".join(lines)


def _figures_block(space: str) -> str:
    label = SPACE_LABELS[space]
    names = [
        (f"umap_cluster_{space}.png", f"Clusters ({label})"),
        (f"umap_pct_ser_thr_pro_{space}.png", f"Ser/Thr/Pro % ({label})"),
        (f"umap_has_signal_peptide_{space}.png", f"Signal peptide presence ({label})"),
        (f"umap_has_cazy_{space}.png", f"CAZy domain presence ({label})"),
    ]
    lines = []
    for fname, alt in names:
        fpath = FIGURES / fname
        if not fpath.exists():
            raise FileNotFoundError(f"Expected figure not found: {fpath}")
        lines.append(f"![{alt}](figures/{fname})")
    return "\n\n".join(lines)


def main() -> None:
    scope_lines = []
    summary_blocks = []
    aa1_blocks = []
    for space in SPACES:
        stats = _scope_stats(space)
        label = SPACE_LABELS[space]
        scope_lines.append(
            f"- **{label}**: {stats['n_proteins']} proteins embedded, "
            f"{stats['n_clusters']} clusters found, "
            f"{stats['n_noise']} noise points ({stats['pct_noise']:.1f}% of the set)."
        )
        summary_blocks.append(f"### {label}\n\n{_cluster_summary_md(space)}")
        aa1_blocks.append(f"### {label}\n\n{_aa1_summary(space)}")

    contingency_summary = _contingency_summary(TABLES / "cluster_contingency_table.csv")

    figures_esm2 = _figures_block("esm2_classifier")
    figures_esmc = _figures_block("esmc300m")

    report = f"""# Embedding-Space Clustering of Fungal Adhesion Proteins

## Scope

{chr(10).join(scope_lines)}

Both cluster summaries are computed by `05_validate_and_compare.py` from
`tables/cluster_labels_{{space}}.csv` (per-protein cluster assignment, produced
by Tasks 3/4/6's real ESM2-classifier-space and ESM-C 300M embedding
extraction + `sklearn.cluster.HDBSCAN` clustering), joined against
`analysis/adhesion_properties/tables/{{protein_sequence_properties,protein_domain_flags}}.csv`.

**Why the two spaces cover slightly different protein counts (749,680 vs.
749,697):** the shipped classifier's own embedding function
(`src/adhesion_predict/embeddings.py`'s `get_esm_embeddings`) silently
drops an entire batch of sequences if any single sequence in it fails to
tokenize. The real ESM2-classifier extraction run lost 176 proteins to
this; 159 were pure batch-collateral-damage and were recovered by
re-running them in isolation (`analysis/embedding_clustering/recover_missing_esm2_embeddings.py`,
committed alongside this report) at `batch_size=1`, same model, same
mathematical result. The remaining 17 genuinely contain `J` or `*`
characters that are not in ESM-2's tokenizer alphabet at all -- these
cannot be embedded in ESM2-classifier space by any batching choice, a
real and permanent limitation of that embedding space (not a bug). ESM-C
300M's tokenizer handles a broader character set and embedded all
749,697 proteins with zero missing. `get_esm_embeddings` itself is
deliberately left unmodified, as it is pre-existing production code for
the shipped classifier, out of scope for this analysis to alter.

## Per-space cluster summary

Each cluster's N, median length, median Ser/Thr/Pro%, mean hydrophobicity,
and domain-flag fractions (`has_pfam`, `has_cazy`, `has_merops`,
`has_signal_peptide`, `has_tm_helix`). Cluster label `-1` is HDBSCAN noise
(not dropped -- reported like any other cluster, per this project's stated
caveat that noise is a real category, not an artifact to hide).

{summary_blocks[0]}

{summary_blocks[1]}

## Agreement between the two embedding spaces (contingency table)

Full cross-tabulation is in `tables/cluster_contingency_table.csv`
(3 ESM2-classifier rows x 513 ESM-C 300M columns -- too wide to render
usefully here as a table, so it is summarized below instead):

{contingency_summary}

## AA1/CAZy concentration by cluster

**Limitation, stated plainly**: this check uses `has_cazy`, a broad "any
CAZy-family domain hit at all" boolean carried in
`protein_domain_flags.csv`. It is **not** a precise per-protein AA1
(laccase/multicopper-oxidase) family flag -- the underlying data does not
carry per-protein AA1-subfamily membership, so `has_cazy` is used here only
as an approximate proxy for "any CAZy domain," which is a superset of the
AA1-specific question the adhesion_properties project's Caveat 7 originally
raised. Any concentration (or lack of it) shown below should not be read as
confirming or ruling out AA1-specific concentration.

{aa1_blocks[0]}

{aa1_blocks[1]}

## Figures

**Note on what these figures show:** the UMAP 2D projection in every
figure below is computed from the *raw* embeddings (480-dim for
ESM2-classifier, 960-dim for ESM-C 300M), while HDBSCAN clustering
(the colors in the "Clusters" figures) was run on a 15-component PCA
reduction of those same embeddings (see Caveat 7). The cluster labels
painted onto each UMAP projection therefore come from a different
(lower-dimensional) representation than the 2D layout itself -- points
that look close in a UMAP plot are not guaranteed to have been "close"
in the space HDBSCAN actually clustered on, and vice versa. This is a
reasonable and common choice (UMAP on the full embedding preserves more
of the original structure for visualization) but is worth keeping in
mind, particularly for the ESM-C 300M cluster figure, whose visual
fragmentation partly reflects this space/space mismatch, not only the
real 512-cluster/86%-noise HDBSCAN result itself.

### ESM2-classifier space

{figures_esm2}

### ESM-C 300M space

{figures_esmc}

## Headline findings

The two embedding spaces give starkly different answers to this project's
motivating question of whether embedding-space clustering reveals distinct
adhesin sub-types: ESM2-classifier space finds only 2 real clusters (one
dominant cluster of 708,322 proteins, 94.5% of the set, plus a tiny 53-protein
second cluster) with just 5.5% noise, while ESM-C 300M space fragments the
same population into 512 real clusters with 86.1% noise (645,515/749,697) and
a largest cluster of only 4,089 proteins (0.55%). So the answer to "does
embedding-space clustering reveal distinct structural sub-types" depends
heavily on which embedding space is used: the classifier-tuned ESM2 space
collapses almost the entire population into one blob and provides very
little discriminative signal on its own, while the raw ESM-C 300M space
resolves fine-grained (if individually small and mostly noise-labeled)
structure. The contingency table shows these spaces largely agree on
outliers but diverge sharply on internal structure: ESM2-classifier's
dominant cluster spreads across 511 of 512 ESM-C clusters (85.6% of it
lands in ESM-C noise, and the largest single non-noise cell is only 0.58%
of the cluster), so ESM-C's fine clustering resolves real internal
structure within the population ESM2-classifier space cannot distinguish,
rather than the two spaces simply disagreeing about where to draw
boundaries around an otherwise-homogeneous population; the two spaces'
noise populations do agree closely (39,449/41,305 = 95.5% overlap). There
is one genuine, specific, checkable cross-space signal: ESM2-classifier's
tiny 53-protein cluster maps 48/53 (90.6%) onto a single ESM-C cluster
(label 66, n=65 total, so ~73.8% of that ESM-C cluster's membership comes
from this same 53-protein ESM2 group), and that ESM-C cluster's own summary
row shows 100% `has_signal_peptide` and 0% `has_tm_helix` (both verified
directly against `cluster_summary_esmc300m.csv`) -- a small but distinctive
shared cluster across both embedding spaces, consistent with a
secreted/GPI-anchored protein architecture (median Ser/Thr/Pro% 44.4%,
also elevated relative to the ~28-30% seen in the larger clusters). As with
every cluster reported here, this specific small-cluster signal has not
been checked for sequence redundancy across genomes (Caveat 9) or run
through a `min_cluster_size` sensitivity sweep (Caveat 8) -- it is a
concrete, checkable candidate for follow-up, not a validated finding on its
own. The AA1/CAZy concentration check (via the `has_cazy` proxy) is essentially
uniform in ESM2-classifier space (20.7% in the dominant cluster, close to
the dataset's 19.9% baseline; std across clusters only 0.108) but sharply
bimodal in ESM-C 300M space (74.5% of clusters at exactly 0% `has_cazy`,
19.1% at exactly 100%; std 0.409) -- ESM-C's finer clustering surfaces real
cluster-level CAZy-domain concentration that the classifier-tuned ESM2
space compresses away.

## Caveats

1. **Exploratory/unsupervised, no significance testing.** HDBSCAN cluster
   assignments and the property/domain summaries above are descriptive.
   No statistical test (e.g. permutation test, ARI significance test) was
   run to establish that either space's clustering is more structured than
   chance, or that any per-cluster property difference is significant.
2. **HDBSCAN noise is reported, not hidden.** Cluster label `-1` appears in
   every summary table above exactly like any other cluster label, per
   this project's design decision that noise is real information (a
   protein HDBSCAN could not confidently assign to any cluster), not a
   category to filter out before reporting.
3. **The AA1/CAZy check is a `has_cazy`-proxy approximation**, not a
   precise per-protein AA1-family flag (see the AA1/CAZy section above for
   the full statement of this limitation).
4. **Embedding models carry their own pretraining biases.** Both ESM-2 and
   ESM-C were pretrained on large public sequence databases with their own
   taxonomic and functional composition biases; cluster structure found
   here reflects what these specific pretrained models encode about
   sequence similarity, not a bias-free ground truth about protein
   structure or function.
5. **Cluster "architecture" identification (FLO11-like/Als-like) is a
   hypothesis suggested by data patterns, not a confirmed structural
   classification.** Any resemblance noted in Headline findings between a
   cluster's property/domain signature and a known adhesin architecture
   (e.g. signal-peptide-positive, TM-helix-negative, Ser/Thr/Pro-rich) is a
   candidate for follow-up biological interpretation, not a validated
   structural or functional annotation.
6. **Prediction-set circularity.** The protein set clustered throughout
   this analysis was itself selected by an ESM-2-embedding-based
   classifier (see `analysis/adhesion_properties/REPORT.md` Caveat 6).
   Clustering on ESM2-classifier-space embeddings -- a variant of that
   same embedding space -- is therefore not fully independent evidence
   about this protein set's internal structure; a clustering result in
   that space partly reflects properties the classifier's own decision
   function was already sensitive to, rather than a wholly separate
   observation. This is a known limitation carried over from the earlier
   adhesion_properties project, not a new one specific to this analysis.
7. **`n_pca_components=15` (vs. `cluster.py`'s default of 50) trades
   fidelity for computational tractability.** Both real clustering runs
   (Task 6) used 15 PCA components, retaining approximately 86-89% of
   variance (88.7% ESM2-classifier, 86.4% ESM-C 300M) versus approximately
   94-95% at 50 components (94.5%/94.8%). This is a real, if modest,
   reduction in fidelity. It was chosen because HDBSCAN's roughly O(n^~2)
   scaling at 50 PCA dimensions on ~750K points was projected to take 9-11
   hours per embedding space; 15 dimensions brought each run into a
   several-hour range (actual: ~2.5h reduce+cluster per space, plus UMAP).
8. **Neither space's clustering result has been checked for sensitivity to
   `min_cluster_size`** (HDBSCAN's density threshold), and both results
   should be read with that in mind, not just the more obviously skewed
   one. ESM2-classifier space's clustering result is borderline-degenerate
   for the scientific purpose of finding structural sub-types, even
   though it technically passes this project's literal "not everything in
   one cluster" completion bar: with 94.5% of all proteins in one dominant
   cluster and only 5.5% in noise (no meaningful second population beyond
   one 53-protein cluster), this space provides very little discriminative
   signal on its own for distinguishing adhesin sub-architectures. But
   ESM-C 300M's result is *also* a single-parameter-setting outcome (86.1%
   noise, 512 clusters, largest cluster only 0.55% of the data, all at the
   same default `min_cluster_size=50`) that has not been swept either --
   language above like "real internal structure" and "real cluster-level
   CAZy-domain concentration" describes what the current parameter choice
   shows, not a result confirmed robust to that choice. A `min_cluster_size`
   sensitivity sweep for BOTH spaces (checking whether either result is an
   artifact of the default value or a robust feature of that embedding
   space) was recommended during this project (Task 6/7/8) but was **not
   performed** for either space -- it is out of scope for the tasks
   completed here and is deferred as a future follow-up. This should not
   be read as having ruled out a different clustering structure at other
   `min_cluster_size` values, for either embedding space.
9. **Proteins in this set were not de-duplicated for sequence redundancy
   across genomes.** The 749,697 proteins come from roughly a thousand
   fungal genomes, so a substantial fraction of any given cluster may be
   orthologs or close paralogs of each other rather than independent
   examples of a shared structural architecture. No identity-threshold
   clustering (e.g. CD-HIT) was applied before HDBSCAN clustering. Some of
   the exact 0.0000/1.0000 domain-flag fractions seen in the ESM-C 300M
   per-cluster summary table above are at least as consistent with "one
   ortholog group, sampled repeatedly across genomes" as with "one
   distinct structural architecture" -- this is a real, unaddressed
   confound for reading ESM-C 300M's 512 clusters as 512 candidate
   sub-architectures, and should be checked (e.g. by inspecting whether a
   cluster's members cluster taxonomically too) before drawing that
   conclusion for any specific cluster.

## Regenerating this report

`tables/cluster_summary_*.csv`, `tables/cluster_contingency_table.csv`, and
`tables/aa1_concentration_by_cluster_*.csv` (read by this script) are
committed directly (small, derived summary tables). The large per-protein
intermediates they are computed from (`tables/cluster_labels_*.csv`, the
embedding `.npy` chunks under `tables/esm2_classifier/` and
`tables/esmc300m/`) are not tracked in git -- they are reproducible from
the same real data source. Regenerate them with
`01_extract_embeddings_esm2_classifier.py` (chunks 0-149 -- see the note
in Scope above: this alone will NOT reproduce the full 749,680-protein
ESM2-classifier set, since Task 3's real run silently dropped 176
proteins; also run `recover_missing_esm2_embeddings.py` afterward to
produce chunk_00150 and recover 159 of those 176),
`02_extract_embeddings_esmc300m.py`, `03_cluster_esm2_classifier.py`,
`04_cluster_esmc300m.py`, then `05_validate_and_compare.py` and
`06_make_figures.py`, before re-running this script.
"""
    (BASE / "REPORT.md").write_text(report)
    print(f"Wrote {BASE / 'REPORT.md'}")


if __name__ == "__main__":
    main()
