#!/usr/bin/env python
"""Assemble REPORT.md from the tables/figures already generated by
01/02/03. Pulls all numbers directly from the CSVs — the only prose this
script does NOT generate is the headline-findings interpretation, which
is written by hand in Step 3 after inspecting the real output."""

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from figures import ranked_summary_table  # noqa: E402

BASE = Path(__file__).resolve().parent
TABLES = BASE / "tables"


def _count_rows(csv_path: Path) -> int:
    return len(pd.read_csv(csv_path)) if csv_path.exists() else 0


def main() -> None:
    species = pd.read_csv(TABLES / "species_adhesion_summary.csv")
    n_matched = len(species)
    n_unmatched = _count_rows(TABLES / "unmatched_species.csv")
    n_mismatched = _count_rows(TABLES / "mismatched_locustag.csv")
    n_missing = _count_rows(TABLES / "missing_results.csv")

    phylum_summary = pd.read_csv(TABLES / "stats_by_phylum.csv")
    order_summary = pd.read_csv(TABLES / "stats_by_order.csv")
    phylum_omnibus = pd.read_csv(TABLES / "stats_by_phylum_omnibus.csv").iloc[0]
    order_omnibus = pd.read_csv(TABLES / "stats_by_order_omnibus.csv").iloc[0]
    phylum_omnibus_genus = pd.read_csv(TABLES / "stats_by_phylum_genus_avg_omnibus.csv").iloc[0]

    mixedlm_rows = {}
    for rank in ("phylum", "class", "order"):
        mixedlm_rows[rank] = pd.read_csv(TABLES / f"mixedlm_by_{rank}.csv").iloc[0]

    def _mixedlm_section(rank: str) -> str:
        row = mixedlm_rows[rank]
        if not bool(row["converged"]):
            return (
                f"- **{rank}**: model did not converge "
                f"(see `tables/mixedlm_by_{rank}_summary.txt` for details)."
            )
        genus_var = float(row["genus_variance"])
        resid_var = float(row["residual_variance"])
        ratio = genus_var / resid_var if resid_var else float("nan")
        if ratio >= 1:
            interp = (
                f"genus variance is ~{ratio:.2g}x the residual variance for {rank}, "
                "indicating substantial non-independence within genus"
            )
        else:
            interp = (
                f"genus variance is ~{ratio:.2g}x the residual variance for {rank} "
                "(smaller than the residual, but still a non-negligible share of the "
                "total variance, so some non-independence within genus remains)"
            )
        return (
            f"- **{rank}**: converged. Genus variance component = {genus_var:.3g}, "
            f"residual variance component = {resid_var:.3g} ({interp}). "
            f"Full model summary: `tables/mixedlm_by_{rank}_summary.txt`."
        )

    report = f"""# Kingdom-wide Fungal Adhesion Protein Survey

## Scope

- {n_matched} species successfully joined to taxonomy and proteome-size data.
- {n_unmatched} species excluded (no LOCUSTAG match or missing .fai) — see `tables/unmatched_species.csv`.
- {n_mismatched} species excluded for a mismatched protein-annotation source — see `tables/mismatched_locustag.csv`.
- {n_missing} species in Fungi_5k have no `adhesion_predict` result file at all — see `tables/missing_results.csv`.

## Headline findings

At the phylum level (well-powered groups, n≥5), Chytridiomycota has the
highest median `adhesion_fraction` (0.0166, n=67 species) and
Microsporidia the lowest (0.0021, n=9); this top/bottom ordering is
unchanged after collapsing species to one value per genus (genus-averaged:
Chytridiomycota 0.0164, n=41 genera; Microsporidia 0.0023, n=6 genera), so
it is not simply an artifact of repeated intra-genus sampling. The phylum
omnibus Kruskal-Wallis test is highly significant either way (naive:
H=1.59e+03, p≈0, epsilon-squared=0.274, n_groups=7; genus-averaged:
H=478, p=5.44e-100, epsilon-squared=0.365) — the genus-averaged effect
size is, if anything, larger, arguing against oversampling as the driver
of the phylum-level signal. At the order level the separation is sharper:
Neocallimastigales (n=8 species) has the single highest median
`adhesion_fraction` (0.0387) and stays on top after genus-averaging
(0.0417, n=5 genera), and the order-level omnibus effect size exceeds the
phylum-level one in both the naive view (H=3.55e+03, epsilon-squared=0.637,
n_groups=84) and the genus-averaged view (H=765, p=2.28e-126,
epsilon-squared=0.714, n_groups=55). The bottom of the order ranking
diverges between the two methods, however: naively, Malasseziales has the
lowest median `adhesion_fraction` among well-powered orders (0.0027,
n=20 species), but under genus-averaging its species collapse into too
few distinct genera to remain in the well-powered set at all (flagged
`small_n`), and the lowest well-powered genus-averaged order becomes
Ustilaginales (0.0052, n=12 genera) instead — a likely oversampling
artifact of Malasseziales specifically, not a robust bottom-of-ranking
signal. Note that the phylum boxplot below does not visually distinguish
its two small-N phyla (Sanchytriomycota, Cryptomycota; both n=1) from the
well-powered ones — a box built from a single point has no visible box
area — so that N imbalance is only legible from the tables, not the
figure itself.

![Adhesion fraction by phylum](figures/box_fraction_by_phylum.png)

![Proteome size vs adhesion count](figures/scatter_proteome_vs_adhesion.png)

The scatter above highlights only the 3 largest phyla by species count
(Ascomycota, Basidiomycota, Zoopagomycota) in distinct colors, with every
other phylum folded into muted gray "Other" — a dense, overlapping
all-pairs scatter cannot safely distinguish more than 3 categorical
colors at once (see `figures.py`'s module docstring), so showing all 9
phyla's own point clouds is left to the small-multiples version below.

![Proteome size vs adhesion count by phylum](figures/scatter_proteome_vs_adhesion_by_phylum.png)

## By phylum

Naive per-species test: H={phylum_omnibus['h_stat']:.3g}, p={phylum_omnibus['p_value']:.3g}, \
epsilon-squared={phylum_omnibus['epsilon_squared']:.3g}, n_groups={int(phylum_omnibus['n_groups'])}.

Genus-averaged test: H={phylum_omnibus_genus['h_stat']:.3g}, p={phylum_omnibus_genus['p_value']:.3g}, \
epsilon-squared={phylum_omnibus_genus['epsilon_squared']:.3g}.

{ranked_summary_table(phylum_summary, "phylum")}

![Mean adhesion probability by phylum](figures/box_prob_by_phylum.png)

## By order (all orders; figures below show top 20 by species count)

Naive per-species test: H={order_omnibus['h_stat']:.3g}, p={order_omnibus['p_value']:.3g}, \
epsilon-squared={order_omnibus['epsilon_squared']:.3g}, n_groups={int(order_omnibus['n_groups'])}.

{ranked_summary_table(order_summary, "order")}

† = small-N (n < MIN_GROUP_N), descriptive only, excluded from formal tests.

![Adhesion fraction by order](figures/box_fraction_by_order.png)

![Mean adhesion probability by order](figures/box_prob_by_order.png)

## Pseudo-phylogenetic correction (mixed model)

A third view alongside naive per-species and genus-averaged tests: a
linear mixed model of `adhesion_fraction ~ C(rank)` with genus as a
random intercept, fit on the same MIN_GROUP_N-filtered species subset as
the other two views (see `stats.py`'s `mixedlm_by_rank`). This
approximates a phylogenetic correction using genus membership as a proxy
for shared ancestry (no real branch lengths). For each rank:

{_mixedlm_section("phylum")}
{_mixedlm_section("class")}
{_mixedlm_section("order")}

Full model output (coefficients, standard errors, z-values) for each rank
is in `tables/mixedlm_by_{{phylum,class,order}}_summary.txt`.

## Family/genus drill-down

**Exploratory / hypothesis-generating — not a pre-registered test.** The
generated `stats_by_order*.csv` tables carry an omnibus epsilon-squared
for the order-level test as a whole (see "By order" above), not a
per-order epsilon-squared broken out group-by-group, so a literal
"top-3-orders-by-epsilon-squared" ranking cannot be read off these
tables. What genuinely is available and used here instead: the top 3
well-powered orders (n≥5, not flagged `small_n`) by median
`adhesion_fraction` from `tables/stats_by_order.csv` — Neocallimastigales
(0.0387, n=8), Orbiliales (0.0321, n=25), and Dothideales (0.0220, n=32)
— broken down by family/genus directly from
`tables/species_adhesion_summary.csv`:

- **Neocallimastigales** (all 8 species in family Neocallimastigaceae —
  the order is monofamilial in this dataset): genus medians range from
  *Pecoramyces* (n=1, median 0.0533) and *Piromyces* (n=3, median 0.0472)
  down to *Neocallimastix* (n=2, median 0.0278) and *Anaeromyces* (n=1,
  median 0.0357), with *Caecomyces* (n=1, median 0.0417) in between — the
  whole order is elevated, but every genus here has n≤3 species, so none
  of these within-order genus differences should be read as more than
  suggestive.
- **Orbiliales** (all 25 species in family Orbiliaceae): the highest
  genus median is *Dactylellina* (n=6, median 0.0371), followed by
  *Orbilia* (n=6, median 0.0323) and *Arthrobotrys* (n=9, median 0.0309),
  with *Dactylella* (n=1, median 0.0243) and *Drechslerella* (n=3, median
  0.0191) lower — i.e. the nematode-trapping genera *Dactylellina* and
  *Arthrobotrys* anchor the high end of this order.
- **Dothideales** (32 species across 4 named families, plus 1 species with
  no family-level taxonomy assigned) is dominated by a single
  family/genus: *Aureobasidium* (family Saccotheciaceae) contributes 26
  of the 32 species with median 0.0223, well above the order's other
  named families/genera (Dothioraceae n=2 median 0.0194; Dothideaceae n=1
  median 0.0181; Zalariaceae/*Zalaria* n=2 median 0.0158) — so Dothideales'
  elevated order-level median is largely a single-genus (*Aureobasidium*)
  signal, not a broad order-wide pattern.

## Caveats

1. **Non-independence beyond genus.** Genus-averaging and a genus-random-
   intercept mixed model correct for oversampled genera, but neither uses
   real branch lengths or divergence times — a true phylogenetic
   comparative method would. Residual non-independence above the genus
   level (shared family/order ancestry) is not corrected for here.
2. **Annotation quality varies by genome** and could confound raw counts;
   mitigated partly by using `adhesion_fraction`, not raw count alone.
3. **Classifier training-set bias.** The model was trained on a small
   positive set (FLO/ALS1-like proteins from *Saccharomyces*/*Candida*);
   it may under-call adhesion-like proteins in very divergent lineages
   whose domains don't resemble the training set. Treat phyla with
   unusually low fractions as a training-bias hypothesis to test, not
   automatically a biological conclusion.
4. **Taxonomic sampling is wildly unbalanced** (phylum N ranges from
   thousands down to 1); Kruskal-Wallis reads as significant on almost
   any real difference at this scale, so epsilon-squared effect size is
   the headline statistic here, not the p-value alone. Groups with
   N < {5} are excluded from formal statistical tests and are colored
   distinctly from well-sampled groups in the code, though for the
   smallest groups (n=1) a boxplot has no visible fill area to show that
   color on — see the note under Headline findings for the specific case
   observed in this run.
5. **`adhesion_fraction` is fixed to the model's internal 0.5 probability
   threshold.** Results files contain only positive calls, so no
   threshold-sensitivity analysis is possible from existing data — a
   different cutoff could shift which clades look "enriched."

## Follow-up

A phylogeny-aware re-analysis (real branch lengths from `nf_phyling`
output or another tree source, e.g. phylogenetic ANOVA / PGLS) is the
natural next step once a tree is available for this species set.
"""
    (BASE / "REPORT.md").write_text(report)
    print(f"Wrote {BASE / 'REPORT.md'}")


if __name__ == "__main__":
    main()
